name: Makefile Action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Make with Debug
      run: make debug

    - name: Make with -Werror -Wextra -Wall
      run: make

    - name: Make with Optimize
      run: make full-optimize
